#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE "${PRODUCT_DB_DB}";
    GRANT ALL PRIVILEGES ON DATABASE "${PRODUCT_DB_DB}" TO "${PRODUCT_DB_USER}";
EOSQL 