services:
  # Auth service database
  auth-db:
    image: postgres:latest
    restart: always
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - ./apps/auth-service/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./docker-data/auth-db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  # Redis service
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./docker-data/redis-data:/data
    networks:
      - backend-network

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web UI
    volumes:
      - ./docker-data/mailhog-data:/var/lib/mailhog
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  auth-db-data:
  redis-data:
