services:
  # Auth service database
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-network
  # Redis service
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./docker-data/redis-data:/data
    networks:
      - backend-network

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web UI
    volumes:
      - ./docker-data/mailhog-data:/var/lib/mailhog
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  auth-db-data:
  redis-data:
