services:
  # Auth service database
  auth-db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    volumes:
      - ./docker-data/auth-db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  # Redis service
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./docker-data/redis-data:/data
    networks:
      - backend-network

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web UI
    volumes:
      - ./docker-data/mailhog-data:/var/lib/mailhog
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  auth-db-data:
  redis-data:
