/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as dashboardRouteImport } from './routes/(dashboard)/route'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as dashboardIndexImport } from './routes/(dashboard)/index'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as dashboardProductsRouteImport } from './routes/(dashboard)/products/route'
import { Route as dashboardProductsIndexImport } from './routes/(dashboard)/products/index'
import { Route as PaymentConnectReturnImport } from './routes/payment/connect/return'
import { Route as PaymentConnectRefreshImport } from './routes/payment/connect/refresh'
import { Route as dashboardProductsNewImport } from './routes/(dashboard)/products/new'

// Create/Update Routes

const dashboardRouteRoute = dashboardRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const dashboardIndexRoute = dashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)

const authResetPasswordRoute = authResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)

const dashboardProductsRouteRoute = dashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => dashboardRouteRoute,
} as any)

const dashboardProductsIndexRoute = dashboardProductsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardProductsRouteRoute,
} as any)

const PaymentConnectReturnRoute = PaymentConnectReturnImport.update({
  id: '/payment/connect/return',
  path: '/payment/connect/return',
  getParentRoute: () => rootRoute,
} as any)

const PaymentConnectRefreshRoute = PaymentConnectRefreshImport.update({
  id: '/payment/connect/refresh',
  path: '/payment/connect/refresh',
  getParentRoute: () => rootRoute,
} as any)

const dashboardProductsNewRoute = dashboardProductsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => dashboardProductsRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/products': {
      id: '/(dashboard)/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof dashboardProductsRouteImport
      parentRoute: typeof dashboardRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof authRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexImport
      parentRoute: typeof dashboardRouteImport
    }
    '/(dashboard)/products/new': {
      id: '/(dashboard)/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof dashboardProductsNewImport
      parentRoute: typeof dashboardProductsRouteImport
    }
    '/payment/connect/refresh': {
      id: '/payment/connect/refresh'
      path: '/payment/connect/refresh'
      fullPath: '/payment/connect/refresh'
      preLoaderRoute: typeof PaymentConnectRefreshImport
      parentRoute: typeof rootRoute
    }
    '/payment/connect/return': {
      id: '/payment/connect/return'
      path: '/payment/connect/return'
      fullPath: '/payment/connect/return'
      preLoaderRoute: typeof PaymentConnectReturnImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/products/': {
      id: '/(dashboard)/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof dashboardProductsIndexImport
      parentRoute: typeof dashboardProductsRouteImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface dashboardProductsRouteRouteChildren {
  dashboardProductsNewRoute: typeof dashboardProductsNewRoute
  dashboardProductsIndexRoute: typeof dashboardProductsIndexRoute
}

const dashboardProductsRouteRouteChildren: dashboardProductsRouteRouteChildren =
  {
    dashboardProductsNewRoute: dashboardProductsNewRoute,
    dashboardProductsIndexRoute: dashboardProductsIndexRoute,
  }

const dashboardProductsRouteRouteWithChildren =
  dashboardProductsRouteRoute._addFileChildren(
    dashboardProductsRouteRouteChildren,
  )

interface dashboardRouteRouteChildren {
  dashboardProductsRouteRoute: typeof dashboardProductsRouteRouteWithChildren
  dashboardIndexRoute: typeof dashboardIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardProductsRouteRoute: dashboardProductsRouteRouteWithChildren,
  dashboardIndexRoute: dashboardIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof dashboardIndexRoute
  '/products': typeof dashboardProductsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/products/new': typeof dashboardProductsNewRoute
  '/payment/connect/refresh': typeof PaymentConnectRefreshRoute
  '/payment/connect/return': typeof PaymentConnectReturnRoute
  '/products/': typeof dashboardProductsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof dashboardIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/products/new': typeof dashboardProductsNewRoute
  '/payment/connect/refresh': typeof PaymentConnectRefreshRoute
  '/payment/connect/return': typeof PaymentConnectReturnRoute
  '/products': typeof dashboardProductsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(dashboard)/products': typeof dashboardProductsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(dashboard)/products/new': typeof dashboardProductsNewRoute
  '/payment/connect/refresh': typeof PaymentConnectRefreshRoute
  '/payment/connect/return': typeof PaymentConnectReturnRoute
  '/(dashboard)/products/': typeof dashboardProductsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/products/new'
    | '/payment/connect/refresh'
    | '/payment/connect/return'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/products/new'
    | '/payment/connect/refresh'
    | '/payment/connect/return'
    | '/products'
  id:
    | '__root__'
    | '/(auth)'
    | '/(dashboard)'
    | '/(dashboard)/products'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(dashboard)/'
    | '/(dashboard)/products/new'
    | '/payment/connect/refresh'
    | '/payment/connect/return'
    | '/(dashboard)/products/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  PaymentConnectRefreshRoute: typeof PaymentConnectRefreshRoute
  PaymentConnectReturnRoute: typeof PaymentConnectReturnRoute
}

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  PaymentConnectRefreshRoute: PaymentConnectRefreshRoute,
  PaymentConnectReturnRoute: PaymentConnectReturnRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)",
        "/(dashboard)",
        "/payment/connect/refresh",
        "/payment/connect/return"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/forgot-password",
        "/(auth)/reset-password",
        "/(auth)/sign-in",
        "/(auth)/sign-up"
      ]
    },
    "/(dashboard)": {
      "filePath": "(dashboard)/route.tsx",
      "children": [
        "/(dashboard)/products",
        "/(dashboard)/"
      ]
    },
    "/(dashboard)/products": {
      "filePath": "(dashboard)/products/route.tsx",
      "parent": "/(dashboard)",
      "children": [
        "/(dashboard)/products/new",
        "/(dashboard)/products/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/reset-password": {
      "filePath": "(auth)/reset-password.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.tsx",
      "parent": "/(auth)"
    },
    "/(dashboard)/": {
      "filePath": "(dashboard)/index.tsx",
      "parent": "/(dashboard)"
    },
    "/(dashboard)/products/new": {
      "filePath": "(dashboard)/products/new.tsx",
      "parent": "/(dashboard)/products"
    },
    "/payment/connect/refresh": {
      "filePath": "payment/connect/refresh.tsx"
    },
    "/payment/connect/return": {
      "filePath": "payment/connect/return.tsx"
    },
    "/(dashboard)/products/": {
      "filePath": "(dashboard)/products/index.tsx",
      "parent": "/(dashboard)/products"
    }
  }
}
ROUTE_MANIFEST_END */
